#Auto-generated PowerShell to encrypt existing data
# Generated by SQL Server Management Studio at 12:54 on 28/01/2022

Import-Module SqlServer
# Set up connection and database SMO objects

$sqlConnectionString = "Data Source=.\MSSQLSERVER01;Initial Catalog=TestAlwaysEncrypted;Integrated Security=True;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;Packet Size=4096;Application Name=`"Microsoft SQL Server Management Studio`""
$smoDatabase = Get-SqlDatabase -ConnectionString $sqlConnectionString

# If your encryption changes involve keys in Azure Key Vault, uncomment one of the lines below in order to authenticate:
#   * Prompt for a username and password:
#Add-SqlAzureAuthenticationContext -Interactive

#   * Enter a Client ID, Secret, and Tenant ID:
#Add-SqlAzureAuthenticationContext -ClientID '<Client ID>' -Secret '<Secret>' -Tenant '<Tenant ID>'

# Change encryption schema

$encryptionChanges = @()

# Add changes for table [dbo].[EncryptingExistingData]
$encryptionChanges += New-SqlColumnEncryptionSettings -ColumnName dbo.EncryptingExistingData.NumericData -EncryptionType Deterministic -EncryptionKey "TestCEK"
$encryptionChanges += New-SqlColumnEncryptionSettings -ColumnName dbo.EncryptingExistingData.TextData -EncryptionType Randomized -EncryptionKey "TestCEK"

Set-SqlColumnEncryption -ColumnEncryptionSettings $encryptionChanges -InputObject $smoDatabase 
